export const Office_Staff = [
  {
    id: 1,
    forenames: "Daniel",
    surname: "Adu-Gyamfi",
    rank: "District Registration Officer",
    email: "dadg@gmail.com",
    contact: "0500000000",
    profilePic: "/assets/images/profilePic.png",
  },
  {
    id: 2,
    forenames: "Joseph Obededom",
    surname: "Eshun",
    rank: "Assistant Administrative Officer",
    email: "josehun@gmail.com",
    contact: "0500000000",
    profilePic: "/assets/images/profilePic.png",
  },
  {
    id: 3,
    forenames: "Lydia",
    surname: "Asraah",
    rank: "Assistant Registration Officer",
    email: "lydiasraah@gmail.com",
    contact: "0500000000",
    profilePic: "/assets/images/profilePic.png",
  },
  {
    id: 4,
    forenames: "Eric Kodzo",
    surname: "Ayi",
    rank: "Assistant Technical Enrollment Officer",
    email: "ayieric7@gmail.com",
    contact: "0500000000",
    profilePic: "/assets/images/profilePic.png",
  },
  {
    id: 5,
    forenames: "Pamela",
    surname: "Manu",
    rank: "National Service Personnel",
    email: "pamanu@gmail.com",
    contact: "0500000000",
    profilePic: "/assets/images/profilePic.png",
  },
];
